modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "copperhorns"
version = "${version}"
displayName = "Copper Goat Horns"
authors = "Isabel Maskrey"
description = '''
Re-adds copper goat horns from the Bedrock Preview
'''
logoFile = "assets/copperhorns/textures/item/copper_goat_horn.png"

[[dependencies.copperhorns]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.copperhorns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.copperhorns]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
